apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: ocp410bf-aci-containers-system-acc-provision-config-configmap-core-v1
spec:
  clusterName: ocp410bf
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: acc-provision-config
    namespace: aci-containers-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"acc-provision-config","namespace":"aci-containers-system","creationTimestamp":null},"data":{"spec":"{\n    \"acc_provision_input\":
    {\n        \"operator_managed_config\": {\n            \"enable_updates\": false\n        },\n        \"aci_config\":
    {\n            \"system_id\": \"ocp410bf\",\n            \"apic_hosts\": [\n                \"10.30.120.61\"\n            ],\n            \"aep\":
    \"ocp-bm-1-servers\",\n            \"vrf\": {\n                \"name\": \"ocp410_bf_vrf\",\n                \"tenant\":
    \"common\"\n            },\n            \"vmm_domain\": {\n                \"type\":
    \"OpenShift\",\n                \"encap_type\": \"vxlan\",\n                \"mcast_fabric\":
    \"225.1.2.3\",\n                \"mcast_range\": {\n                    \"start\":
    \"225.10.1.1\",\n                    \"end\": \"225.10.255.255\",\n                }\n                \"nested_inside\":
    {\n                    \"type\": \"vmware\"\n                    \"name\": \"HX_vC\"\n                    \"installer_provisioned_lb_ip\":
    \"192.168.1.2\"\n                }\n            },\n            \"l3out\": {\n                \"name\":
    \"ocp410_bf_l3out\",\n                \"external_networks\": [\n                    \"ocp-bf-l3-extepg\"\n                ]\n            }\n        },\n        \"registry\":
    {\n            \"image_prefix\": \"quay.io/noirolabs\", \n            \"image_pull_secret\":
    \"noiro-docker-registry-secret\"\n        },\n        \"kube_config\": {\n            \"image_pull_policy\":
    \"Always\", \n            \"ovs_memory_limit\": \"1Gi\"\n\n        },\n        \"logging\":
    {\n           \"controller_log_level\": \"debug\", \n           \"hostagent_log_level\":
    \"debug\", \n           \"opflexagent_log_level\": \"debug\"\n        },\n        \"net_config\":
    {\n            \"infra_vlan\": 4093,\n            \"service_vlan\": 201, \n            \"kubeapi_vlan\":
    200,\n            \"extern_static\": \"10.4.0.1/24\",\n            \"extern_dynamic\":
    \"10.3.0.1/24\",\n            \"node_svc_subnet\": \"10.5.0.1/24\",\n            \"node_subnet\":
    \"192.168.1.1/24\",\n            \"pod_subnet\": \"10.2.0.1/16\"\n        }\n    }\n
    }"}}'
status:
  state: ""
